#!/usr/bin/env python
import sys
from argparse import ArgumentParser

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-w', '--width', type=int, default=25)
    args = parser.parse_args()

    for line in sys.stdin.readlines():
        fields = line.strip().split('\t')
        print '\t'.join(('%%-%ds' % args.width) % field for field in fields)

