#!/bin/sh

# E.g. diffg was now --word-diff

# TODO: should be `git-diff --word-diff was now`

a="$1"
b="$2"
shift 2

tmpdir=$(basename "$0")-$(date '+%Y%m%d%H%M%S')
mkdir "$tmpdir" && ln "$a" "$tmpdir"/a || exit 1
(cd "$tmpdir" && git init && git add a) > /dev/null
ln -f "$b" "$tmpdir"/a
(cd "$tmpdir" && git diff --color=always $@ | sed -n '/@@/,$p' | less -FRSX)
rm -rf "$tmpdir" || {
    echo "Failed to remove temp dir $tmpdir"
    exit 1
}
