#!/bin/sh

# E.g. diffg was now --word-diff

# TODO: should be `git-diff --word-diff was now`

a="$1"
b="$2"
shift 2

tmpdir=/tmp/$(basename "$0")-$(date '+%Y%m%d%H%M%S')
mkdir $tmpdir && cp "$a" $tmpdir/a && cp "$b" $tmpdir/b || exit 1
cd $tmpdir
(git init && git add a && git commit -m `basename "$a"`) > /dev/null
mv b a
(git add a && git commit -m `basename "$b"`) > /dev/null
git show --color=always $@ | sed -n '/@@/,$p' | less -FRSX
[ $? ] && rm -fr $tmpdir
