#!/bin/bash

emacsclient --no-wait \
    --eval "(magit-status \"$PWD\")" \
    --eval "(magit-diff \"master...\")" \
    --eval "(progn (select-frame-set-input-focus (selected-frame)) (delete-other-windows))" > /dev/null
