#!/bin/bash

# An extra layer of quoting is present because the arguments are passed over ssh
emacsclient-remote \
    --no-wait \
    --eval \'"(progn (magit-status \"$PWD\") (select-frame-set-input-focus (selected-frame)))"\'
