#!/bin/sh

_is_osx () {
    [ -e /Applications ]
}

EMACSCLIENT=/usr/local/bin/emacsclient

if _is_osx ; then
     $EMACSCLIENT $@
else
    echo "Remote not currently implemented." 1>&2
    echo "String value of emacsclient --eval needs to be wrapped in \\'" 1>&2
    # ssh 10.0.2.2 "cd $PWD && $EMACSCLIENT $@"
    exit 1
fi
