#!/bin/sh

_is_osx () {
    [ -e /Applications ]
}

if _is_osx ; then
    HOST_ADDRESS=localhost
else
    HOST_ADDRESS=10.0.2.2
fi

HOST_EMACSCLIENT=/usr/local/bin/emacsclient

ssh $HOST_ADDRESS "cd $PWD && $HOST_EMACSCLIENT $@"
