#!/bin/sh

# E.g. git-diff was now --word-diff

# TODO: should be `git-diff --word-diff was now`

a="$1"
b="$2"
shift 2

dir=/tmp/`date '+%Y%m%d%H%M%S'`
mkdir $dir && cp "$a" $dir/a && cp "$b" $dir/b || exit 1
cd $dir
(git init && git add a && git commit -m `basename "$a"`) > /dev/null
mv b a
(git add a && git commit -m `basename "$b"`) > /dev/null
git show $@
