#!/bin/bash

[ -n "$1" ] && [ -n "$2" ] || {
    echo "$0: n branch" 1>&2
    exit 2
}

git log --oneline "$2" \
    | head -n "$1" \
    | cut -d' ' -f1 \
    | tac \
    | while read commit ; do git cherry-pick $commit ; done
