#!/bin/bash
dirs=$(cat <<EOF
comm
design
document_control
it
market
plot.js
science/bin
science/build
science/common_modules
science/data
science/doc
science/experimental_code
science/include
science/lib
science/package
science/protocols
science/test
science/test_oneoff
science/ui
science/util
science/product
site/build
site/doc
site/include
site/setup
EOF
)
dirs=$(echo $dirs)
cmd="find $dirs -type f | xargs git update-index --assume-unchanged"
echo $cmd
$cmd
