#!/bin/sh

path="$1"
regex="$2"
[ -f "$path" ] || {
    echo "No such file: $path" && exit 1
}

git log --oneline "$path" | cut -d' ' -f1 | while read commit ; do
    git-cat $commit "$path" | grep -q "$regex" && echo "$commit has it" || break
done
