#!/usr/bin/env python
import sys
import json
from jsonpipe import jsonpipe


if __name__ == '__main__':
    with (open(sys.argv[1]) if len(sys.argv) > 1 else sys.stdin) as fp:
        for line in jsonpipe(json.load(fp)):
            print line
