#!/usr/bin/env python
import json
import sys

JSON_DUMP_KWARGS = {
    'indent': 2,
    'sort_keys': True,
    'allow_nan': False
}

with file(sys.argv[1]) as fp:
    obj = json.load(fp)

with file(sys.argv[1], 'w') as fp:
    json.dump(obj, fp, **JSON_DUMP_KWARGS)
