#!/usr/bin/env python
REGEXP = (r"https://github\..+\.com/"
          "(?P<organization>[^/]+)/"
          "(?P<repo>[^/]+)/"
          "(blob|tree|raw)/"
          "(?P<branch>[^/]+)/"
          "(?P<path>.+)")


if __name__ == '__main__':
    import subprocess
    import re
    import os
    import sys

    REPOS_DIR = os.getenv('HOME')

    url, err = subprocess.Popen(['reattach-to-user-namespace', 'pbpaste'],
                                stdout=subprocess.PIPE).communicate()
    if err:
        print >>sys.stderr, err
        sys.exit(1)
    match = re.compile(REGEXP).match(url)
    if not match:
        print >>sys.stderr, 'URL not recognized: %s' % url
        sys.exit(1)

    match = match.groupdict()
    subprocess.call(
        ['open',
         os.path.join(REPOS_DIR,
                      match['repo'],
                      match['path'])])
