#!/usr/bin/env python
import os
import re
import sys

path, text_after = sys.argv[1:]
[line_num] = re.compile('[^"]*", line (\d+), ').match(text_after).groups()
line_num = int(line_num)

cmd = (
    '/usr/local/bin/emacsclient --no-wait '
    '--eval "(find-file \\"%s\\")" '
    '--eval "(goto-line %d)" '
    '--eval "(select-frame-set-input-focus (selected-frame))"'
) % (path, line_num)

os.system(cmd)
