#!/usr/bin/env python
import json
import yaml
import sys

instream = sys.stdin
outstream = sys.stdout

if len(sys.argv) > 1:
    instream = file(sys.argv[1])
if len(sys.argv) > 2:
    assert len(sys.argv) == 3
    outstream = file(sys.argv[2], 'w')

json.dump(yaml.load(instream), outstream, indent=2)
